//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Floreview.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Floreview.Resources.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Door.
        /// </summary>
        public static string Blog_Author {
            get {
                return ResourceManager.GetString("Blog_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geplaatst op.
        /// </summary>
        public static string Blog_Datetime {
            get {
                return ResourceManager.GetString("Blog_Datetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geen GSM nummer beschikbaar.
        /// </summary>
        public static string Detail_Contact_Mobile_Error {
            get {
                return ResourceManager.GetString("Detail_Contact_Mobile_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geen telefoonnummer beschikbaar.
        /// </summary>
        public static string Detail_Contact_Phone_Error {
            get {
                return ResourceManager.GetString("Detail_Contact_Phone_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geen website beschikbaar.
        /// </summary>
        public static string Detail_Contact_Website_Error {
            get {
                return ResourceManager.GetString("Detail_Contact_Website_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nederlands.
        /// </summary>
        public static string Footer_Language_Dutch {
            get {
                return ResourceManager.GetString("Footer_Language_Dutch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engels.
        /// </summary>
        public static string Footer_Language_English {
            get {
                return ResourceManager.GetString("Footer_Language_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frans.
        /// </summary>
        public static string Footer_Language_French {
            get {
                return ResourceManager.GetString("Footer_Language_French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duits.
        /// </summary>
        public static string Footer_Language_German {
            get {
                return ResourceManager.GetString("Footer_Language_German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to door.
        /// </summary>
        public static string Home_Blog_Promotion_Author {
            get {
                return ResourceManager.GetString("Home_Blog_Promotion_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to geplaatst op.
        /// </summary>
        public static string Home_Blog_Promotion_Datetime {
            get {
                return ResourceManager.GetString("Home_Blog_Promotion_Datetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recente blogs.
        /// </summary>
        public static string Home_Blog_Promotion_Title {
            get {
                return ResourceManager.GetString("Home_Blog_Promotion_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gemeente.
        /// </summary>
        public static string Home_Search_City_Placeholder {
            get {
                return ResourceManager.GetString("Home_Search_City_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naam.
        /// </summary>
        public static string Home_Search_Name_Placeholder {
            get {
                return ResourceManager.GetString("Home_Search_Name_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoeken.
        /// </summary>
        public static string Home_Search_Submit {
            get {
                return ResourceManager.GetString("Home_Search_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ik zoek een bloemenwinkel.
        /// </summary>
        public static string Home_Search_Title {
            get {
                return ResourceManager.GetString("Home_Search_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelieve een wachtwoord in te vullen..
        /// </summary>
        public static string Login_Password_Error {
            get {
                return ResourceManager.GetString("Login_Password_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wachtwoord.
        /// </summary>
        public static string Login_Password_Placeholder {
            get {
                return ResourceManager.GetString("Login_Password_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aanmelden.
        /// </summary>
        public static string Login_Submit {
            get {
                return ResourceManager.GetString("Login_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aanmelden.
        /// </summary>
        public static string Login_Title {
            get {
                return ResourceManager.GetString("Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelieve een gebruikersnaam in te vullen..
        /// </summary>
        public static string Login_Username_Error {
            get {
                return ResourceManager.GetString("Login_Username_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gebruikersnaam.
        /// </summary>
        public static string Login_Username_Placeholder {
            get {
                return ResourceManager.GetString("Login_Username_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inloggegevens niet correct..
        /// </summary>
        public static string Login_Validation_Message {
            get {
                return ResourceManager.GetString("Login_Validation_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basis informatie.
        /// </summary>
        public static string Manage_AddBlog_BasicInformation {
            get {
                return ResourceManager.GetString("Manage_AddBlog_BasicInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release datum.
        /// </summary>
        public static string Manage_AddBlog_PublishDate_Placeholder {
            get {
                return ResourceManager.GetString("Manage_AddBlog_PublishDate_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opslaan.
        /// </summary>
        public static string Manage_AddBlog_Submit {
            get {
                return ResourceManager.GetString("Manage_AddBlog_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korte beschrijving (DE).
        /// </summary>
        public static string Manage_AddBlog_Teaser_DE {
            get {
                return ResourceManager.GetString("Manage_AddBlog_Teaser_DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korte beschrijving (EN).
        /// </summary>
        public static string Manage_AddBlog_Teaser_EN {
            get {
                return ResourceManager.GetString("Manage_AddBlog_Teaser_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korte beschrijving (FR).
        /// </summary>
        public static string Manage_AddBlog_Teaser_FR {
            get {
                return ResourceManager.GetString("Manage_AddBlog_Teaser_FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korte beschrijving (NL).
        /// </summary>
        public static string Manage_AddBlog_Teaser_NL {
            get {
                return ResourceManager.GetString("Manage_AddBlog_Teaser_NL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titel (DE).
        /// </summary>
        public static string Manage_AddBlog_Title_DE {
            get {
                return ResourceManager.GetString("Manage_AddBlog_Title_DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titel (EN).
        /// </summary>
        public static string Manage_AddBlog_Title_EN {
            get {
                return ResourceManager.GetString("Manage_AddBlog_Title_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titel (FR).
        /// </summary>
        public static string Manage_AddBlog_Title_FR {
            get {
                return ResourceManager.GetString("Manage_AddBlog_Title_FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titel (NL).
        /// </summary>
        public static string Manage_AddBlog_Title_NL {
            get {
                return ResourceManager.GetString("Manage_AddBlog_Title_NL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelieve een adres in te vullen..
        /// </summary>
        public static string Manage_AddStore_Address_Error {
            get {
                return ResourceManager.GetString("Manage_AddStore_Address_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres.
        /// </summary>
        public static string Manage_AddStore_Address_Placeholder {
            get {
                return ResourceManager.GetString("Manage_AddStore_Address_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelieve een gemeente in te vullen..
        /// </summary>
        public static string Manage_AddStore_City_Error {
            get {
                return ResourceManager.GetString("Manage_AddStore_City_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gemeente.
        /// </summary>
        public static string Manage_AddStore_City_Placeholder {
            get {
                return ResourceManager.GetString("Manage_AddStore_City_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lange beschrijving (DE).
        /// </summary>
        public static string Manage_AddStore_Description_Long_DE {
            get {
                return ResourceManager.GetString("Manage_AddStore_Description_Long_DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lange beschrijving (EN).
        /// </summary>
        public static string Manage_AddStore_Description_Long_EN {
            get {
                return ResourceManager.GetString("Manage_AddStore_Description_Long_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lange beschrijving (FR).
        /// </summary>
        public static string Manage_AddStore_Description_Long_FR {
            get {
                return ResourceManager.GetString("Manage_AddStore_Description_Long_FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lange beschrijving (NL).
        /// </summary>
        public static string Manage_AddStore_Description_Long_NL {
            get {
                return ResourceManager.GetString("Manage_AddStore_Description_Long_NL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korte beschrijving (DE).
        /// </summary>
        public static string Manage_AddStore_Description_Short_DE {
            get {
                return ResourceManager.GetString("Manage_AddStore_Description_Short_DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korte beschrijving (EN).
        /// </summary>
        public static string Manage_AddStore_Description_Short_EN {
            get {
                return ResourceManager.GetString("Manage_AddStore_Description_Short_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korte beschrijving (FR).
        /// </summary>
        public static string Manage_AddStore_Description_Short_FR {
            get {
                return ResourceManager.GetString("Manage_AddStore_Description_Short_FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korte beschrijving (NL).
        /// </summary>
        public static string Manage_AddStore_Description_Short_NL {
            get {
                return ResourceManager.GetString("Manage_AddStore_Description_Short_NL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschrijving.
        /// </summary>
        public static string Manage_AddStore_Description_Title {
            get {
                return ResourceManager.GetString("Manage_AddStore_Description_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelieve een Facebook profiel in te vullen..
        /// </summary>
        public static string Manage_AddStore_Facebook_Error {
            get {
                return ResourceManager.GetString("Manage_AddStore_Facebook_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook.
        /// </summary>
        public static string Manage_AddStore_Facebook_Placeholder {
            get {
                return ResourceManager.GetString("Manage_AddStore_Facebook_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelieve een e-mail in te vullen..
        /// </summary>
        public static string Manage_AddStore_Florist_Email_Error {
            get {
                return ResourceManager.GetString("Manage_AddStore_Florist_Email_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string Manage_AddStore_Florist_Email_Placeholder {
            get {
                return ResourceManager.GetString("Manage_AddStore_Florist_Email_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelieve een correct e-mail in te vullen..
        /// </summary>
        public static string Manage_AddStore_Florist_Email_REGEX_Error {
            get {
                return ResourceManager.GetString("Manage_AddStore_Florist_Email_REGEX_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelieve een voornaam in te vullen..
        /// </summary>
        public static string Manage_AddStore_Florist_FirstName_Error {
            get {
                return ResourceManager.GetString("Manage_AddStore_Florist_FirstName_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Een voornaam heeft min. 2 en max. 35 karakters..
        /// </summary>
        public static string Manage_AddStore_Florist_FirstName_Length_Error {
            get {
                return ResourceManager.GetString("Manage_AddStore_Florist_FirstName_Length_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voornaam.
        /// </summary>
        public static string Manage_AddStore_Florist_Firstname_Placeholder {
            get {
                return ResourceManager.GetString("Manage_AddStore_Florist_Firstname_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelieve een achternaam in te vullen..
        /// </summary>
        public static string Manage_AddStore_Florist_LastName_Error {
            get {
                return ResourceManager.GetString("Manage_AddStore_Florist_LastName_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Een achternaam heeft min. 2 en max. 35 karakters..
        /// </summary>
        public static string Manage_AddStore_Florist_LastName_Length_Error {
            get {
                return ResourceManager.GetString("Manage_AddStore_Florist_LastName_Length_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achternaam.
        /// </summary>
        public static string Manage_AddStore_Florist_Lastname_Placeholder {
            get {
                return ResourceManager.GetString("Manage_AddStore_Florist_Lastname_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GSM.
        /// </summary>
        public static string Manage_AddStore_Florist_Mobile_Placeholder {
            get {
                return ResourceManager.GetString("Manage_AddStore_Florist_Mobile_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelieve een correct GSM nummer in te vullen. (+324).
        /// </summary>
        public static string Manage_AddStore_Florist_Mobile_REGEX_Error {
            get {
                return ResourceManager.GetString("Manage_AddStore_Florist_Mobile_REGEX_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefoon.
        /// </summary>
        public static string Manage_AddStore_Florist_Phone_Placeholder {
            get {
                return ResourceManager.GetString("Manage_AddStore_Florist_Phone_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelieve een correct telefoonnummer in te vullen. (+329).
        /// </summary>
        public static string Manage_AddStore_Florist_Phone_REGEX_Error {
            get {
                return ResourceManager.GetString("Manage_AddStore_Florist_Phone_REGEX_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Florist.
        /// </summary>
        public static string Manage_AddStore_Florist_Title {
            get {
                return ResourceManager.GetString("Manage_AddStore_Florist_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winkel.
        /// </summary>
        public static string Manage_AddStore_Store_Title {
            get {
                return ResourceManager.GetString("Manage_AddStore_Store_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelieve een naam in te vullen..
        /// </summary>
        public static string Manage_AddStore_StoreName_Error {
            get {
                return ResourceManager.GetString("Manage_AddStore_StoreName_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Een winkel heeft min. 2 en max. 30 karakters..
        /// </summary>
        public static string Manage_AddStore_StoreName_Length_Error {
            get {
                return ResourceManager.GetString("Manage_AddStore_StoreName_Length_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naam.
        /// </summary>
        public static string Manage_AddStore_StoreName_Placeholder {
            get {
                return ResourceManager.GetString("Manage_AddStore_StoreName_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opslaan.
        /// </summary>
        public static string Manage_AddStore_Submit {
            get {
                return ResourceManager.GetString("Manage_AddStore_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelieve een correcte website in te vullen..
        /// </summary>
        public static string Manage_AddStore_Website_Error {
            get {
                return ResourceManager.GetString("Manage_AddStore_Website_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string Manage_AddStore_Website_Placeholder {
            get {
                return ResourceManager.GetString("Manage_AddStore_Website_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toevoegen.
        /// </summary>
        public static string Manage_Store_Add_Blog {
            get {
                return ResourceManager.GetString("Manage_Store_Add_Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toevoegen.
        /// </summary>
        public static string Manage_Store_Add_Store {
            get {
                return ResourceManager.GetString("Manage_Store_Add_Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoeken.
        /// </summary>
        public static string Manage_Store_Search_Placeholder {
            get {
                return ResourceManager.GetString("Manage_Store_Search_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gemeente.
        /// </summary>
        public static string Manage_Store_Select_City {
            get {
                return ResourceManager.GetString("Manage_Store_Select_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naam.
        /// </summary>
        public static string Manage_Store_Select_Name {
            get {
                return ResourceManager.GetString("Manage_Store_Select_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provincie.
        /// </summary>
        public static string Manage_Store_Select_Province {
            get {
                return ResourceManager.GetString("Manage_Store_Select_Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laatst toegevoegd.
        /// </summary>
        public static string Manage_Store_Select_Recent {
            get {
                return ResourceManager.GetString("Manage_Store_Select_Recent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blogs.
        /// </summary>
        public static string Menu_Admin_Blogs {
            get {
                return ResourceManager.GetString("Menu_Admin_Blogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winkels.
        /// </summary>
        public static string Menu_Admin_Stores {
            get {
                return ResourceManager.GetString("Menu_Admin_Stores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        public static string Menu_Blog {
            get {
                return ResourceManager.GetString("Menu_Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Menu_Contact {
            get {
                return ResourceManager.GetString("Menu_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floreview.
        /// </summary>
        public static string Menu_Floreview {
            get {
                return ResourceManager.GetString("Menu_Floreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Menu_Home {
            get {
                return ResourceManager.GetString("Menu_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aanmelden.
        /// </summary>
        public static string Menu_Login {
            get {
                return ResourceManager.GetString("Menu_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hallo.
        /// </summary>
        public static string Menu_Login_Welcome {
            get {
                return ResourceManager.GetString("Menu_Login_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afmelden.
        /// </summary>
        public static string Menu_Logout {
            get {
                return ResourceManager.GetString("Menu_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gemeente.
        /// </summary>
        public static string Search_Information_City {
            get {
                return ResourceManager.GetString("Search_Information_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naam.
        /// </summary>
        public static string Search_Information_Name {
            get {
                return ResourceManager.GetString("Search_Information_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resultaten.
        /// </summary>
        public static string Search_Information_Results {
            get {
                return ResourceManager.GetString("Search_Information_Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winkels in de buurt.
        /// </summary>
        public static string Search_Nearby_Companies {
            get {
                return ResourceManager.GetString("Search_Nearby_Companies", resourceCulture);
            }
        }
    }
}
