//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Floreview.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Floreview.Resources.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to door.
        /// </summary>
        public static string Home_Blog_Promotion_Author {
            get {
                return ResourceManager.GetString("Home_Blog_Promotion_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to geplaatst op.
        /// </summary>
        public static string Home_Blog_Promotion_Datetime {
            get {
                return ResourceManager.GetString("Home_Blog_Promotion_Datetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recente blogs.
        /// </summary>
        public static string Home_Blog_Promotion_Title {
            get {
                return ResourceManager.GetString("Home_Blog_Promotion_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gemeente.
        /// </summary>
        public static string Home_Search_City_Placeholder {
            get {
                return ResourceManager.GetString("Home_Search_City_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naam.
        /// </summary>
        public static string Home_Search_Name_Placeholder {
            get {
                return ResourceManager.GetString("Home_Search_Name_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoeken.
        /// </summary>
        public static string Home_Search_Submit {
            get {
                return ResourceManager.GetString("Home_Search_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ik zoek een bloemenwinkel.
        /// </summary>
        public static string Home_Search_Title {
            get {
                return ResourceManager.GetString("Home_Search_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winkels.
        /// </summary>
        public static string Menu_Admin_Stores {
            get {
                return ResourceManager.GetString("Menu_Admin_Stores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        public static string Menu_Blog {
            get {
                return ResourceManager.GetString("Menu_Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Menu_Contact {
            get {
                return ResourceManager.GetString("Menu_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floreview.
        /// </summary>
        public static string Menu_Floreview {
            get {
                return ResourceManager.GetString("Menu_Floreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Menu_Home {
            get {
                return ResourceManager.GetString("Menu_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aanmelden.
        /// </summary>
        public static string Menu_Login {
            get {
                return ResourceManager.GetString("Menu_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hallo.
        /// </summary>
        public static string Menu_Login_Welcome {
            get {
                return ResourceManager.GetString("Menu_Login_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afmelden.
        /// </summary>
        public static string Menu_Logout {
            get {
                return ResourceManager.GetString("Menu_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gemeente.
        /// </summary>
        public static string Search_Information_City {
            get {
                return ResourceManager.GetString("Search_Information_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naam.
        /// </summary>
        public static string Search_Information_Name {
            get {
                return ResourceManager.GetString("Search_Information_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resultaten.
        /// </summary>
        public static string Search_Information_Results {
            get {
                return ResourceManager.GetString("Search_Information_Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winkels in de buurt.
        /// </summary>
        public static string Search_Nearby_Companies {
            get {
                return ResourceManager.GetString("Search_Nearby_Companies", resourceCulture);
            }
        }
    }
}
